### ISSUE TITLE
your blog website 's date is wrong

### ISSUE THREAD

**Issue by Nakolu** [elijahbai/elijahbai.github.io#1]
I visited you   [website](https://www.bigbai.fun/)  at 10/29, but your time is up to 11/03😲, If it's not set up intentionally, it's a problem with your website.

**Comment by elijahbai** [comment]
Sorry, it's my fault. I used to write another one in case i would forget next week! 
I'm glead you point out my mistake. I will recorrect it soon.
If you have any questions, tell me anytime. Thank you! 




------------------ 原始邮件 ------------------
发件人: "honulu"<notifications@github.com>;
发送时间: 2019年10月29日(星期二) 上午9:07
收件人: "elijahbai/elijahbai.github.io"<elijahbai.github.io@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [elijahbai/elijahbai.github.io] your blog website 's date is wrong(#1)




I visited you   website  at 10/29, but your time is up to 11/03, If it's not set up intentionally, it's a problem with your website.
